export const data = [
  {
    key: 1,
    name: "Project Del Sol",
    mobileImage: "portfolio/mobile/image-228b.jpg",
    tabletImage: "portfolio/tablet/image-228b.jpg",
    desktopImage: "portfolio/desktop/image-228b.jpg",
  },
  {
    key: 2,
    name: "228B Tower",
    mobileImage: "portfolio/mobile/image-del-sol.jpg",
    tabletImage: "portfolio/tablet/image-del-sol.jpg",
    desktopImage: "portfolio/desktop/image-del-sol.jpg",
  },
  {
    key: 3,
    name: "Le Prototype",
    mobileImage: "portfolio/mobile/image-edelweiss.jpg",
    tabletImage: "portfolio/tablet/image-edelweiss.jpg",
    desktopImage: "portfolio/desktop/image-edelweiss.jpg",
  },
  {
    key: 4,
    name: "Project Del Sol",
    mobileImage: "portfolio/mobile/image-eebox.jpg",
    tabletImage: "portfolio/tablet/image-eebox.jpg",
    desktopImage: "portfolio/desktop/image-eebox.jpg",
  },
  {
    key: 5,
    name: "228B Tower",
    mobileImage: "portfolio/mobile/image-federal.jpg",
    tabletImage: "portfolio/tablet/image-federal.jpg",
    desktopImage: "portfolio/desktop/image-federal.jpg",
  },
  {
    key: 6,
    name: "Le Prototype",
    mobileImage: "portfolio/mobile/image-hypers.jpg",
    tabletImage: "portfolio/tablet/image-hypers.jpg",
    desktopImage: "portfolio/desktop/image-hypers.jpg",
  },
  {
    key: 7,
    name: "Project Del Sol",
    mobileImage: "portfolio/mobile/image-netcry.jpg",
    tabletImage: "portfolio/tablet/image-netcry.jpg",
    desktopImage: "portfolio/desktop/image-netcry.jpg",
  },
  {
    key: 8,
    name: "228B Tower",
    mobileImage: "portfolio/mobile/image-paramour.jpg",
    tabletImage: "portfolio/tablet/image-paramour.jpg",
    desktopImage: "portfolio/desktop/image-paramour.jpg",
  },
  {
    key: 9,
    name: "228B Tower",
    mobileImage: "portfolio/mobile/image-prototype.jpg",
    tabletImage: "portfolio/tablet/image-prototype.jpg",
    desktopImage: "portfolio/desktop/image-prototype.jpg",
  },
  {
    key: 10,
    name: "Le Prototype",
    mobileImage: "portfolio/mobile/image-seraph.jpg",
    tabletImage: "portfolio/tablet/image-seraph.jpg",
    desktopImage: "portfolio/desktop/image-seraph.jpg",
  },
  {
    key: 11,
    name: "Project Del Sol",
    mobileImage: "portfolio/mobile/image-sxiv.jpg",
    tabletImage: "portfolio/tablet/image-sxiv.jpg",
    desktopImage: "portfolio/desktop/image-sxiv.jpg",
  },
  {
    key: 12,
    name: "228B Tower",
    mobileImage: "portfolio/mobile/image-trinity.jpg",
    tabletImage: "portfolio/tablet/image-trinity.jpg",
    desktopImage: "portfolio/desktop/image-trinity.jpg",
  },
];
